openapi: 3.0.0
info:
  title: OpenData Investments API - Open Finance Brasil
  description: |
    The APIs described in this document refer to the Investments API of the OpenData phase of Open Finance Brasil.
  version: 1.0.1
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
tags:
  - name: Funds
    description: Method to obtain the list of Investment Funds
  - name: Bank Fixed Incomes
    description: 'Method to obtain the list of Bank Fixed Income products (CDB, RDB, LCI, and LCA)'
  - name: Credit Fixed Incomes
    description: 'Method to obtain the list of Credit Fixed Income products (Debenture, CRI, and CRA)'
  - name: Variable Incomes
    description: Method to obtain the list of information on Variable Income products (Stocks and Index Funds)
  - name: Treasure Titles # Treasury Bonds
    description: Method to obtain information on Treasury Bonds (Tesouro Direto)
paths:
  /funds:
    get:
      tags:
        - Funds
      summary: Set of information for Investment Funds
      operationId: investmentsGetFunds
      description: Method to obtain the list of Investment Funds
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseInvestmentsFund'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '529':
          $ref: '#/components/responses/SiteIsOverloaded'
  /bank-fixed-incomes:
    get:
      tags:
        - Bank Fixed Incomes
      summary: 'Set of information for Bank Fixed Income products (CDB, RDB, LCI, and LCA)'
      operationId: investmentsGetFixedIncomeBank
      description: 'Method to obtain the list of Bank Fixed Income products (CDB, RDB, LCI, and LCA)'
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseInvestmentsFixedIncomeBank'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '529':
          $ref: '#/components/responses/SiteIsOverloaded'
  /credit-fixed-incomes:
    get:
      tags:
        - Credit Fixed Incomes
      summary: 'Set of information for Credit Fixed Income products (Debenture, CRI, and CRA)'
      operationId: investmentsGetFixedIncomeCredit
      description: 'Method to obtain the list of Credit Fixed Income products (Debenture, CRI, and CRA)'
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseInvestmentsFixedIncomeCredit'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '529':
          $ref: '#/components/responses/SiteIsOverloaded'
  /variable-incomes:
    get:
      tags:
        - Variable Incomes
      summary: Set of information for Variable Income products (Stocks and Index Funds)
      operationId: investmentsGetVariableIncome
      description: Method to obtain the list of information on Variable Income products (Stocks and Index Funds)
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseInvestmentsVariableIncome'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '529':
          $ref: '#/components/responses/SiteIsOverloaded'
  /treasure-titles:
    get:
      tags:
        - Treasure Titles  # Treasury Bonds
      summary: Set of information for Treasury Bonds (Tesouro Direto)
      operationId: investmentsGetTreasure
      description: Method to obtain information on Treasury Bonds (Tesouro Direto)
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseInvestmentsTreasure'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '529':
          $ref: '#/components/responses/SiteIsOverloaded'
components:
  schemas:
    OKResponseInvestmentsFund:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/InvestmentsFund'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/OpenDataMeta'
      additionalProperties: false
    OKResponseInvestmentsFixedIncomeBank:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/InvestmentsFixedIncomeBank'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/OpenDataMeta'
      additionalProperties: false
    OKResponseInvestmentsFixedIncomeCredit:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/InvestmentsFixedIncomeCredit'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/OpenDataMeta'
      additionalProperties: false
    OKResponseInvestmentsVariableIncome:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/InvestmentsVariableIncome'
          example:
            - participant:
                brand: Organização # Organization
                name: Organização A1 # Organization A1
                cnpjNumber: '13456789000112'
                urlComplementaryList: 'https://empresaa1.com/companies'
              investmentType: ACOES # SHARES
              custodyFee:
                prices:
                  - interval: 1_FAIXA # 1_RANGE
                    value: '0.020300'
                    operationRate: '0.500000'
                  - interval: 2_FAIXA # 2_RANGE
                    value: '0.030600'
                    operationRate: '0.100000'
                  - interval: 3_FAIXA # 3_RANGE
                    value: '0.034300'
                    operationRate: '0.300000'
                  - interval: 4_FAIXA # 4_RANGE
                    value: '0.246800'
                    operationRate: '0.100000'
                minimum: '0.010000'
                maximum: '0.300000'
              loadingRate:
                prices:
                  - interval: 1_FAIXA # 1_RANGE
                    value: '0.020300'
                    operationRate: '0.500000'
                  - interval: 2_FAIXA # 2_RANGE
                    value: '0.030600'
                    operationRate: '0.100000'
                  - interval: 3_FAIXA # 3_RANGE
                    value: '0.034300'
                    operationRate: '0.300000'
                  - interval: 4_FAIXA # 4_RANGE
                    value: '0.246800'
                    operationRate: '0.100000'
                minimum: '0.010000'
                maximum: '0.300000'
              targetAudience: PESSOA_JURIDICA # LEGAL_PERSON
            - participant:
                brand: Organização # Organization
                name: Organização A1 # Organization A1
                cnpjNumber: '13456789000112'
                urlComplementaryList: 'https://empresaa1.com/companies'
              investmentType: FUNDO_INDICES # INDEX_FUNDS
              custodyFee:
                prices:
                  - interval: 1_FAIXA # 1_RANGE
                    value: '0.020300'
                    operationRate: '0.500000'
                  - interval: 2_FAIXA # 2_RANGE
                    value: '0.030600'
                    operationRate: '0.100000'
                  - interval: 3_FAIXA # 3_RANGE
                    value: '0.034300'
                    operationRate: '0.300000'
                  - interval: 4_FAIXA # 4_RANGE
                    value: '0.246800'
                    operationRate: '0.100000'
                minimum: '0.010000'
                maximum: '0.300000'
              loadingRate:
                prices:
                  - interval: 1_FAIXA # 1_RANGE
                    value: '0.020300'
                    operationRate: '0.500000'
                  - interval: 2_FAIXA # 2_RANGE
                    value: '0.030600'
                    operationRate: '0.100000'
                  - interval: 3_FAIXA # 3_RANGE
                    value: '0.034300'
                    operationRate: '0.300000'
                  - interval: 4_FAIXA # 4_RANGE
                    value: '0.246800'
                    operationRate: '0.100000'
                minimum: '0.010000'
                maximum: '0.300000'
              targetAudience: PESSOA_JURIDICA # LEGAL_PERSON
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/OpenDataMeta2Records'
      additionalProperties: false
    OKResponseInvestmentsTreasure:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/InvestmentsTreasure'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/OpenDataMeta'
      additionalProperties: false
    NoIdentificationFrequencyDistribution:
      type: object
      description: Frequency distribution.
      required:
        - prices
        - minimum
        - maximum
      properties:
        prices:
          type: array
          description: Price distribution.
          items:
            $ref: '#/components/schemas/DistributionFrequencyPrice'
          minItems: 4
          maxItems: 4
          example:
            - interval: 1_FAIXA # 1_RANGE
              value: '0.020300'
              operationRate: '0.500000'
            - interval: 2_FAIXA # 2_RANGE
              value: '0.030600'
              operationRate: '0.100000'
            - interval: 3_FAIXA # 3_RANGE
              value: '0.034300'
              operationRate: '0.300000'
            - interval: 4_FAIXA # 4_RANGE
              value: '0.246800'
              operationRate: '0.100000'
        minimum:
          type: string
          description: Minimum value.
          minLength: 8
          maxLength: 8
          pattern: '^\d{1}\.\d{6}$'
          example: '0.010000'
        maximum:
          type: string
          description: Maximum value.
          minLength: 8
          maxLength: 8
          pattern: '^\d{1}\.\d{6}$'
          example: '0.300000'
      additionalProperties: false
    InvestmentsNoIdentificationFrequencyDistribution:
      type: object
      description: Frequency distribution.
      required:
        - prices
        - minimum
        - maximum
      properties:
        prices:
          type: array
          description: Price distribution.
          items:
            $ref: '#/components/schemas/DistributionFrequencyPrice'
          minItems: 4
          maxItems: 4
          example:
            - interval: 1_FAIXA # 1_RANGE
              value: '0.020300'
              operationRate: '0.500000'
            - interval: 2_FAIXA # 2_RANGE
              value: '0.030600'
              operationRate: '0.100000'
            - interval: 3_FAIXA # 3_RANGE
              value: '0.034300'
              operationRate: '0.300000'
            - interval: 4_FAIXA # 4_RANGE
              value: '0.246800'
              operationRate: '0.100000'
        minimum:
          type: string
          description: Minimum value.
          minLength: 8
          maxLength: 8
          pattern: '^\d{1}\.\d{6}$'
          example: '0.019800'
        maximum:
          type: string
          description: Maximum value.
          maxLength: 8
          minLength: 8
          pattern: '^\d{1}\.\d{6}$'
          example: '0.019800'
      additionalProperties: false
    DistributionFrequencyPrice:
      type: object
      required:
        - interval
        - value
        - operationRate
      properties:
        interval:
          $ref: '#/components/schemas/EnumInterval'
        value:
          type: string
          description: Median.
          example: '0.019800'
          minLength: 8
          maxLength: 8
          pattern: '^\d{1}\.\d{6}$'
        operationRate:
          type: string
          description: Operation percentage.
          example: '0.019800'
          minLength: 8
          maxLength: 8
          pattern: '^\d{1}\.\d{6}$'
      additionalProperties: false
    EnumDistinctTargetAudience:
      type: string
      description: Target audience (INDIVIDUAL_PERSON or LEGAL_PERSON).
      enum:
        - PESSOA_NATURAL # INDIVIDUAL_PERSON
        - PESSOA_JURIDICA # LEGAL_PERSON
      example: PESSOA_JURIDICA # LEGAL_PERSON
    InvestmentsFixedIncomeBank:
      type: object
      required:
        - participant
        - issuerInstitutionCnpjNumber
        - issuerInstitutionName
        - investmentType
        - index
        - investmentConditions
        - targetAudience
      properties:
        participant:
          $ref: '#/components/schemas/InvestmentsParticipant'
        issuerInstitutionCnpjNumber:
          type: string
          description: Issuer institution CNPJ.
          maxLength: 14
          pattern: '^\d{14}$'
          example: '45086338000178'
        issuerInstitutionName:
          type: string
          maxLength: 250
          minLength: 1
          pattern: \w+\W*
          example: Organização A1 # Organization A1
          description: Issuer institution name.
        investmentType:
          $ref: '#/components/schemas/EnumInvestmentsFixedIncomeBankProductType'
        index:
          $ref: '#/components/schemas/InvestmentsFixedIncomeBankIndex'
        investmentConditions:
          $ref: '#/components/schemas/InvestmentsFixedIncomeBankInvestmentConditions'
        targetAudience:
          $ref: '#/components/schemas/EnumDistinctTargetAudience'
      additionalProperties: false
    InvestmentsFixedIncomeBankIndex:
      type: object
      required:
        - indexer
        - issueRemunerationRate
      properties:
        indexer:
          $ref: '#/components/schemas/EnumInvestmentsFixedIncomeBankIndexer'
        indexerAdditionalInfo:
          type: string
          description: |
            Free text field to fill in additional information regarding the charge.

            [Restriction] Mandatory when "indexer" is equal to 'OTHERS'.
          maxLength: 140
          example: Informações adicionais # Additional information
          pattern: '[\w\W\s]*'
        issueRemunerationRate:
          $ref: '#/components/schemas/InvestmentsNoIdentificationFrequencyDistribution'
      additionalProperties: false
    InvestmentFundMinimumAmount:
      type: object
      required:
        - value
        - currency
      properties:
        value:
          type: string
          description: Minimum amount of the first contribution.
          minLength: 4
          maxLength: 19
          pattern: '^\d{1,16}\.\d{2}$'
          example: '100000.12'
        currency:
          type: string
          pattern: '^[A-Z]{3}$'
          maxLength: 3
          description: 'Currency related to the monetary value, following the ISO-4217 model.'
          example: BRL
      additionalProperties: false
    InvestmentsFixedIncomeBankInvestmentConditions:
      type: object
      required:
        - minimumAmount
        - redemptionTerm
        - expirationPeriod
        - gracePeriod
      properties:
        minimumAmount:
          type: string
          description: Minimum investment amount in the asset.
          minLength: 4
          maxLength: 19
          pattern: '^\d{1,16}\.\d{2}$'
          example: '100.00'
        redemptionTerm:
          $ref: '#/components/schemas/EnumInvestmentsFixedIncomeBankRedemptionTerm'
        expirationPeriod:
          $ref: '#/components/schemas/EnumExpirationGracePeriod'
        gracePeriod:
          $ref: '#/components/schemas/EnumExpirationGracePeriod'
      additionalProperties: false
    InvestmentsFixedIncomeCredit:
      type: object
      required:
        - participant
        - investmentType
        - custodyFee
        - loadingRate
        - targetAudience
      properties:
        participant:
          $ref: '#/components/schemas/InvestmentsParticipant'
        investmentType:
          $ref: '#/components/schemas/EnumInvestmentsFixedIncomeCreditInvestmentType'
        custodyFee:
          $ref: '#/components/schemas/NoIdentificationFrequencyDistribution'
        loadingRate:
          $ref: '#/components/schemas/NoIdentificationFrequencyDistribution'
        targetAudience:
          $ref: '#/components/schemas/EnumDistinctTargetAudience'
      additionalProperties: false
    InvestmentsFund:
      type: object
      required:
        - participant
        - name
        - cnpjNumber
        - admin
        - fundManager
        - anbimaCategory
        - generalConditions
        - taxation
        - fees
      properties:
        participant:
          $ref: '#/components/schemas/InvestmentsParticipant'
        name:
          type: string
          description: Official name of the investment fund.
          pattern: '[\w\W\s]*'
          maxLength: 250
          example: FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS DE INVESTIMENTO # INVESTMENT FUND IN SHARES OF INVESTMENT FUNDS
        cnpjNumber:
          type: string
          description: Investment fund CNPJ.
          maxLength: 14
          pattern: '^\d{14}$'
          example: '64108803000191'
        isinCode:
          type: string
          description: 'Universal code that identifies each security or financial instrument, according to ISO 6166 Standard.<br><br>DEFINITION: ISIN (International Securities Identification Number) is a code that identifies a security, according to ISO 6166 standard.<br>STRUCTURE<br>ISIN is an alphanumeric code that has 12 characters with the following structure:<ul><li>a prefix, composed of 2 alpha characters, which identifies the country code (ISO 3166 Standard);</li><li>the basic number, composed of 9 alphabetic or numeric characters in its extension;</li><li>a numeric check digit.</li></ul>'
          maxLength: 12
          minLength: 12
          pattern: '^[A-Z]{2}([A-Z0-9]){9}\d{1}$'
          example: BRAAAAAAA000
        admin:
          $ref: '#/components/schemas/InvestmentsFundAdmin'
        fundManager:
          $ref: '#/components/schemas/InvestmentsFundFundManager'
        anbimaCategory:
          $ref: '#/components/schemas/EnumInvestmentsFundProductAnbimaCategory'
        fees:
          $ref: '#/components/schemas/InvestmentsFundFees'
        generalConditions:
          $ref: '#/components/schemas/InvestmentsFundGeneralConditions'
        taxation:
          $ref: '#/components/schemas/EnumInvestmentsFundTaxation'
      additionalProperties: false
    InvestmentsFundAdmin:
      type: object
      required:
        - name
        - cnpjNumber
      properties:
        name:
          type: string
          description: Corporate name of the legal entity authorized by the CVM to act as a securities portfolio administrator and responsible for fund administration.
          maxLength: 100
          pattern: '[\w\W\s]*'
          example: ADM OPEN FINANCE DTVM S.A. # ADM OPEN FINANCE DTVM S.A.
        cnpjNumber:
          type: string
          description: Administrator CNPJ.
          maxLength: 14
          pattern: '^\d{14}$'
          example: '14511732000150'
      additionalProperties: false
    InvestmentsFundFundManager:
      type: object
      required:
        - name
        - cnpjNumber
      properties:
        name:
          type: string
          description: Natural or legal person responsible for the professional management of securities portfolio assets authorized by the CVM.
          maxLength: 100
          pattern: '[\w\W\s]*'
          example: GESTOR OPEN FINANCE DTVM S.A. # MANAGER OPEN FINANCE DTVM S.A.
        cnpjNumber:
          type: string
          description: Investment fund manager CNPJ.
          maxLength: 14
          pattern: '^\d{14}$'
          example: '16332711000101'
      additionalProperties: false
    InvestmentsFundFees:
      type: object
      required:
        - maxAdminFee
      properties:
        maxAdminFee:
          type: string
          description: 'Maximum fee charged to remunerate the administrator and other service providers of the fund. If there is no difference between Maximum and Minimum, consider the fund''s administration fee.'
          minLength: 8
          maxLength: 8
          pattern: '^\d{1}\.\d{6}$'
          example: '0.020000'
        entryFee:
          type: string
          description: 'Fee charged at the time of application, which is levied on the amount invested in the fund.'
          minLength: 8
          maxLength: 8
          pattern: '^\d{1}\.\d{6}$'
          example: '0.010000'
        performanceFee:
          $ref: '#/components/schemas/InvestmentsFundFeesPerformanceFee'
        exitFee:
          type: string
          description: Fee paid by the quotaholder when redeeming funds from a fund.
          minLength: 8
          maxLength: 8
          pattern: '^\d{1}\.\d{6}$'
          example: '0.030000'
      additionalProperties: false
    InvestmentsFundFeesPerformanceFee:
      type: object
      properties:
        method:
          $ref: '#/components/schemas/EnumInvestmentsFundFeesPerformanceFeeMethod'
        benchmark:
          $ref: '#/components/schemas/EnumInvestmentsFundFeesPerformanceFeeBenchmark'
        benchmarkAdditionalInfo:
          type: string
          description: Field to be filled in by participants when there are 'Others' in the 'Performance Fee - Benchmark' field.
        amount:
          type: string
          description: Fee charged to the fund based on performance according to rules set out in the fund's regulations.
          minLength: 3
          maxLength: 8
          pattern: '^\d{1}\.\d{1,6}$'
          example: '0.050000'
      additionalProperties: false
    InvestmentsFundGeneralConditionsRedemption:
      type: object
      required:
        - quotationDays
        - quotationTerm
        - paymentDays
        - paymentTerm
      properties:
        quotationDays:
          type: integer
          format: int32
          description: Maximum period in days indicated in the fund's regulations for the conversion of quotas into cash.
          example: 3
          minimum: 0
          maximum: 2147483647
        quotationTerm:
          $ref: '#/components/schemas/EnumInvestmentsFundGeneralConditionsTermType'
        paymentDays:
          type: integer
          format: int32
          description: 'Maximum period in days for the effective payment, by the fund, of the net amount due to the quotaholder who requested redemption.'
          example: 3
          minimum: 0
          maximum: 2147483647
        paymentTerm:
          $ref: '#/components/schemas/EnumInvestmentsFundGeneralConditionsTermType'
        graceDays:
          type: integer
          format: int32
          description: 'Establishes a period in number of calendar days in which the investor cannot redeem the funds invested in the fund. If redemption occurs before the period, the investor will lose the profitability of the period. If it does not exist, do not inform the field.'
          example: 365
          minimum: 0
          maximum: 2147483647
      additionalProperties: false
    InvestmentsFundGeneralConditionsApplication:
      type: object
      required:
        - quotationDays
        - quotationTerm
      properties:
        quotationDays:
          type: integer
          format: int32
          description: Period in days indicated in the fund's regulations for the conversion of money into fund shares.
          example: 60
          minimum: 0
          maximum: 2147483647
        quotationTerm:
          $ref: '#/components/schemas/EnumInvestmentsFundGeneralConditionsTermType'
      additionalProperties: false
    InvestmentsFundGeneralConditions:
      type: object
      required:
        - minimumAmount
        - redemption
        - application
        - fundQuotaType
      properties:
        minimumAmount:
          $ref: '#/components/schemas/InvestmentFundMinimumAmount'
        redemption:
          $ref: '#/components/schemas/InvestmentsFundGeneralConditionsRedemption'
        application:
          $ref: '#/components/schemas/InvestmentsFundGeneralConditionsApplication'
        fundQuotaType:
          $ref: '#/components/schemas/EnumInvestmentsFundGeneralConditionsFundQuotaType'
      additionalProperties: false
    InvestmentsTreasure:
      type: object
      required:
        - investmentType
        - custodyFee
        - loadingRate
        - participant
      properties:
        participant:
          $ref: '#/components/schemas/InvestmentsParticipant'
        investmentType:
          $ref: '#/components/schemas/EnumInvestmentsTreasureInvestmentType'
        custodyFee:
          $ref: '#/components/schemas/InvestmentsNoIdentificationFrequencyDistribution'
        loadingRate:
          $ref: '#/components/schemas/InvestmentsNoIdentificationFrequencyDistribution'
      additionalProperties: false
    InvestmentsVariableIncome:
      type: object
      required:
        - participant
        - investmentType
        - custodyFee
        - loadingRate
        - targetAudience
      properties:
        participant:
          $ref: '#/components/schemas/InvestmentsParticipant'
        investmentType:
          $ref: '#/components/schemas/EnumInvestmentsVariableIncomeInvestmentType'
        custodyFee:
          $ref: '#/components/schemas/NoIdentificationFrequencyDistribution'
        loadingRate:
          $ref: '#/components/schemas/NoIdentificationFrequencyDistribution'
        targetAudience:
          $ref: '#/components/schemas/EnumDistinctTargetAudience'
      additionalProperties: false
    EnumInvestmentsFixedIncomeBankIndexer:
      type: string
      description: |
        – Any operation with mixed rate in CDI, DI, SELIC must be ignored - only rates without coupon will be considered
        – In the case of pre-fixed, only the coupon will be used, even if there is another mixed indexer
        – In the case of TR, IPCA, IGP_M, IGP_DI, INPC, BCP, TLC AND OTHERS, the calculation will be made on top of the coupon (even if it is zero), disregarding operations that have an indexer other than 100%

        Calculation rules per indexer
        ▪ CDI = % OF CDI
        ▪ DI = % OF DI
        ▪ TR = TR + COUPON
        ▪ IPCA = IPCA + COUPON
        ▪ IGP_M = IGP_M + COUPON
        ▪ IGP_DI = IGP_DI + COUPON
        ▪ INPC = INPC + COUPON
        ▪ BCP = BCP + COUPON
        ▪ TLC = TLC + COUPON
        ▪ SELIC = % OF SELIC
        ▪ PRE_FIXADO = COUPON
        ▪ OUTROS = Indexer + Coupon
      enum:
        - CDI
        - DI
        - TR
        - IPCA
        - IGP_M
        - IGP_DI
        - INPC
        - BCP
        - TLC
        - SELIC
        - PRE_FIXADO # PRE_FIXED
        - OUTROS # OTHERS
      example: CDI
    EnumInvestmentsFixedIncomeBankProductType:
      type: string
      description: Specification of the asset in question.<br><ol><li>CDB</li><li>RDB</li><li>LCI</li><li>LCA</li></ol>
      enum:
        - CDB
        - RDB
        - LCI
        - LCA
      example: CDB
    EnumInvestmentsFixedIncomeBankRedemptionTerm:
      type: string
      description: Ability to convert the security into cash (redemption or repurchase).<br><br><ol><li>daily</li><li>on maturity date</li><li>daily after grace period</li></ol>
      enum:
        - DIARIA # DAILY
        - DATA_VENCIMENTO # MATURITY_DATE
        - DIARIA_PRAZO_CARENCIA # DAILY_GRACE_PERIOD
      example: DIARIA # DAILY
    EnumInvestmentsFixedIncomeCreditInvestmentType:
      type: string
      description: Specifies the type of asset traded:<br><br><ol><li>Debentures</li><li>CRI</li><li>CRA</li></ol>
      enum:
        - DEBENTURES
        - CRI
        - CRA
      example: CRI
    EnumInvestmentsFundFeesPerformanceFeeBenchmark:
      type: string
      description: 'Index used as a reference for evaluating the performance of the investment fund.<br><br>In line with standardization in the listing of ANBIMA funds, with the option “others”, allowing a free field if the option is not previously provided. Benchmark listing available at link https://data.anbima.com.br/fundos , option Characteristics > Benchmark'
      enum:
        - CDI
        - IBOVESPA_FECHAMENTO # IBOVESPA_CLOSING
        - IBOVESPA
        - IMA_B
        - IBRX
        - IPCA
        - IMA_B_5
        - DOLAR_PTAX # DOLLAR_PTAX
        - IBRX_100
        - TAXA_SELIC # SELIC_RATE
        - IMA_B_5_PLUS
        - IBOVESPA_MEDIO # IBOVESPA_MEDIUM
        - IRF_M
        - IMA_GERAL # IMA_GENERAL
        - INPC
        - IGP_M
        - SMLL_SMALL_CAP
        - IDA_IPCA
        - ISE
        - IRF_M_1
        - IBRX_50
        - IDIV_DIVIDENDOS # IDIV_DIVIDENDS
        - IFIX
        - GLOBAL_BDRX
        - IMA_S
        - IDKA_IPCA_2A
        - IRF_M_1_PLUS
        - OUTROS # OTHERS
      example: CDI
    EnumInvestmentsFundFeesPerformanceFeeMethod:
      type: string
      description: Methodology of the field for performance fee.<br><ol><li>Passive</li><li>Active</li><li>Adjustment</li></ol>
      enum:
        - PASSIVO # PASSIVE
        - ATIVO # ACTIVE
        - AJUSTE # ADJUSTMENT
      example: PASSIVO # PASSIVE
    EnumInvestmentsFundGeneralConditionsFundQuotaType:
      type: string
      description: Regarding the incidence of taxes on the investment product:<br><br><ol><li>Opening quota</li><li>Closing quota</li></ol>
      enum:
        - COTA_ABERTURA # OPENING_QUOTA
        - COTA_FECHAMENTO # CLOSING_QUOTA
      example: COTA_ABERTURA # OPENING_QUOTA
    EnumInvestmentsFundGeneralConditionsTermType:
      type: string
      description: Period in calendar days or business days of the quotation period.<br><br><ol><li>Calendar days</li><li>Business days</li></ol>
      enum:
        - DIAS_CORRIDOS # CALENDAR_DAYS
        - DIAS_UTEIS # BUSINESS_DAYS
      example: DIAS_CORRIDOS # CALENDAR_DAYS
    EnumInvestmentsFundProductAnbimaCategory:
      type: string
      description: |
        As per ANBIMA classification (ANBIMA is the Brazilian association for self-regulation of financial and capital markets):

        - Fixed Income

        - Stocks

        - Multi-market

        - Exchange
      enum:
        - RENDA_FIXA   # FIXED_INCOME
        - ACOES        # STOCKS
        - MULTIMERCADO # MULTI_MARKET
        - CAMBIAL      # EXCHANGE
      example: MULTIMERCADO # MULTI_MARKET
    EnumInvestmentsFundTaxation:
      type: string
      description: 'Indicates the type of taxation, which can be:<br><ol><li>Short term</li><li>Long term</li><li>Variable</li></ol>'
      enum:
        - CURTO_PRAZO # SHORT_TERM
        - LONGO_PRAZO # LONG_TERM
        - VARIAVEL    # VARIABLE
      example: CURTO_PRAZO # SHORT_TERM
    EnumInvestmentsTreasureInvestmentType:
      type: string
      description: Specifies the type of asset traded, Treasury Bonds (Tesouro Direto)
      enum:
        - TESOURO_DIRETO # TREASURY_BONDS (TESOURO DIRETO)
      example: TESOURO_DIRETO # TREASURY_BONDS (TESOURO DIRETO)
    EnumInvestmentsVariableIncomeInvestmentType:
      type: string
      description: Specifies the type of asset traded:<br><br><ol><li>Stocks</li><li>Index fund</li></ol>
      enum:
        - ACOES # SHARES
        - FUNDO_INDICES # INDEX_FUNDS
      example: ACOES # SHARES
    InvestmentsParticipant:
      type: object
      description: Set of information regarding the Open Finance product participant
      required:
        - brand
        - name
        - cnpjNumber
      properties:
        brand:
          type: string
          description: 'Brand name reported by the Open Finance participant. The concept referred to by ''brand'' is essentially a company''s promise to provide a specific series of uniform attributes, benefits and services to customers.'
          maxLength: 80
          pattern: '[\w\W\s]*'
          example: Organização # Organization
        name:
          type: string
          description: Name of the Open Finance participant.
          maxLength: 80
          pattern: '[\w\W\s]*'
          example: Organização A1 # Organization A1
        cnpjNumber:
          $ref: '#/components/schemas/CnpjNumber'
        urlComplementaryList:
          type: string
          format: url
          description: |
            It is expected that the return value, after accessing the ‘urlComplementaryList’ link, must be an object array with the structure below:

            - ‘name’ with the value contained in the ‘LegalEntityName’ field as registered in the directory;

            - 'cnpjNumber' with the value contained in the CNPJ (‘RegistrationNumber’) field corresponding to this institution;

            - Both of string type;

            - Both mandatory.
          maxLength: 1024
          example: 'https://empresaa1.com/companies'
      additionalProperties: false
    EnumInterval:
      type: string
      description: Frequency ranges
      enum:
        - 1_FAIXA # 1_RANGE
        - 2_FAIXA # 2_RANGE
        - 3_FAIXA # 3_RANGE
        - 4_FAIXA # 4_RANGE
      example: 1_FAIXA # 1_RANGE
    CnpjNumber:
      type: string
      description: 'CNPJ is the registration number in the National Registry of Legal Entities. Only the CNPJ numbers should be provided, without mask.'
      maxLength: 14
      pattern: '^\d{14}$'
      example: '13456789000112'
    Links:
      type: object
      description: References to other resources of the requested API.
      required:
        - self
      properties:
        self:
          type: string
          format: url
          maxLength: 2000
          description: Full URI that generated the current response.
          example: 'https://api.banco.com.br/open-banking/api/v1/resource'
        first:
          type: string
          format: url
          maxLength: 2000
          description: URI of the first page that originated this list of results. Restriction - Mandatory when not the first page of the response
          example: 'https://api.banco.com.br/open-banking/api/v1/resource'
        prev:
          type: string
          format: url
          maxLength: 2000
          description: "URI of the previous page of this list of results. Restriction - \tMandatory when not the first page of the response"
          example: 'https://api.banco.com.br/open-banking/api/v1/resource'
        next:
          type: string
          format: url
          maxLength: 2000
          description: URI of the next page of this list of results. Restriction - Mandatory when not the last page of the response
          example: 'https://api.banco.com.br/open-banking/api/v1/resource'
        last:
          type: string
          format: url
          maxLength: 2000
          description: URI of the last page of this list of results. Restriction - Mandatory when not the last page of the response
          example: 'https://api.banco.com.br/open-banking/api/v1/resource'
      additionalProperties: false
    OpenDataMeta:
      type: object
      description: Meta information regarding the requested API.
      required:
        - totalRecords
        - totalPages
      properties:
        totalRecords:
          type: integer
          format: int32
          description: Total number of records in the result
          example: 1
        totalPages:
          type: integer
          format: int32
          description: Total number of pages in the result
          example: 1
      additionalProperties: false
    OpenDataMeta2Records:
      type: object
      description: Meta information regarding the requested API.
      required:
        - totalRecords
        - totalPages
      properties:
        totalRecords:
          type: integer
          format: int32
          description: Total number of records in the result
          example: 2
        totalPages:
          type: integer
          format: int32
          description: Total number of pages in the result
          example: 1
      additionalProperties: false
    OpenDataResponseError:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          minItems: 1
          maxItems: 13
          items:
            type: object
            required:
              - code
              - title
              - detail
            properties:
              code:
                description: Specific endpoint error code
                type: string
                pattern: '[\w\W\s]*'
                maxLength: 255
              title:
                description: Human-readable title for this specific error
                type: string
                pattern: '[\w\W\s]*'
                maxLength: 255
              detail:
                description: Human-readable description of this specific error
                type: string
                pattern: '[\w\W\s]*'
                maxLength: 2048
            additionalProperties: false
        meta:
          $ref: '#/components/schemas/OpenDataMeta'
      additionalProperties: false
    EnumExpirationGracePeriod:
      type: string
      enum:
        - '1_360'
        - '361_1080'
        - 1081+
      example: 1081+
      description: |
        Range of values for maturity and grace periods.
  parameters:
    page:
      name: page
      in: query
      description: Page number being requested (the value of the first page is 1).
      schema:
        type: integer
        default: 1
        minimum: 1
        maximum: 2147483647
        format: int32
    pageSize:
      name: page-size
      in: query
      description: Total number of records per page.
      schema:
        type: integer
        default: 25
        minimum: 1
        format: int32
        maximum: 1000
  responses:
    OKResponseInvestmentsFund:
      description: Investment fund data successfully obtained.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OKResponseInvestmentsFund'
    OKResponseInvestmentsFixedIncomeBank:
      description: Bank fixed income product data successfully obtained.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OKResponseInvestmentsFixedIncomeBank'
    OKResponseInvestmentsFixedIncomeCredit:
      description: Credit fixed income product data successfully obtained.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OKResponseInvestmentsFixedIncomeCredit'
    OKResponseInvestmentsVariableIncome:
      description: Variable income product data successfully obtained.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OKResponseInvestmentsVariableIncome'
    OKResponseInvestmentsTreasure:
      description: Treasury bonds (Tesouro Direto) bond data successfully obtained.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OKResponseInvestmentsTreasure'
    BadRequest:
      description: 'The request was malformed, omitting mandatory attributes, either in the payload or through attributes in the URL.'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/OpenDataResponseError'
    InternalServerError:
      description: An error occurred in the API gateway or microservice
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/OpenDataResponseError'
    MethodNotAllowed:
      description: The consumer attempted to access the resource with an unsupported method
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/OpenDataResponseError'
    NotFound:
      description: The requested resource does not exist or has not been implemented
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/OpenDataResponseError'
    TooManyRequests:
      description: 'The operation was refused because too many requests were made within a certain period or the concurrent request limit was reached.'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/OpenDataResponseError'
    SiteIsOverloaded:
      description: 'The site is overloaded and the operation was refused because the global TPS maximum limit was reached at this time.'
      content:
        application/json; charset=utf-8:
          schema:
            type: object
            required:
              - errors
            properties:
              errors:
                type: array
                minItems: 1
                maxItems: 13
                items:
                  type: object
                  required:
                    - code
                    - title
                    - detail
                  properties:
                    code:
                      description: Specific endpoint error code
                      type: string
                      pattern: '[\w\W\s]*'
                      maxLength: 255
                    title:
                      description: Human-readable title for this specific error
                      type: string
                      pattern: '[\w\W\s]*'
                      maxLength: 255
                    detail:
                      description: Human-readable description of this specific error
                      type: string
                      pattern: '[\w\W\s]*'
                      maxLength: 2048
              meta:
                type: object
                description: Meta information regarding the requested API.
                required:
                  - requestDateTime
                properties:
                  requestDateTime:
                    description: 'Date and time of the query, according to RFC-3339 specification, UTC format.'
                    type: string
                    maxLength: 20
                    format: date-time
                    example: '2021-05-21T08:30:00Z'
